apps/base/urls.py
from django.conf.urls import url, include
from apps.base.views import index

from django.urls import include, path

app_name = "base";

urlpatterns = [
url(r'^$', index,name='index'),
]

apps/sistema/urls.py
from django.conf.urls import url, include
from apps.sistema.views import index,listar_usuarios,User_edit,registrarproductos,listar_productos,Contrato,VerContrato,registrartransportes
from apps.sistema.views import solicitarpedido,listar_pedidos,AdministrarPedido,OfertaProducto,lista_ofrecer,lista_procesopedidos,ResponderOfertas
from apps.sistema.views import lista_sin_transporte,OfertarTransporte,lista_en_proceso,ResponderTransportes,Eliminar_ofert_transport,SolicitarSeguimientos
from apps.sistema.views import lista_en_seguimiento,seguimiento_admin,AdministrarSeguimientos
from django.urls import include, path

app_name = "sistema";

urlpatterns = [
    url(r'^$', index,name='index'),
    url(r'^usuarios/', listar_usuarios,name='usuarios'),
    url(r'^editar/(?P<id_user>\d*)$', User_edit, name='editar_usuario'),
    url(r'^registrarprod/', registrarproductos,name='regprod'),
    url(r'^listaprod/', listar_productos, name='listaprod'),
    url(r'^mi-contrato/',VerContrato,name='mi-contrato'),
    url(r'^contrato/', Contrato, name='regcontr'),
    url(r'^registrartrans/', registrartransportes,name='regptrans'),
    url(r'^solicitar-pedido/', solicitarpedido,name='solped'),
    url(r'^listapedid/', listar_pedidos, name='listaped'),
    url(r'^administrar-pedido/(?P<id_ped>\d*)$', AdministrarPedido, name='administrarpedido'),
    url(r'^lista-sin-ofertas/', lista_ofrecer, name='listasinofertas'),
    url(r'^oferta-transporte/(?P<id_ped>\d*)$', OfertaProducto, name='ofertatransporte'),
    url(r'^mis-pedidos/', lista_procesopedidos, name='mispedidos'),
    url(r'^responder-oferta/(?P<id_ped>\d*)$', ResponderOfertas, name='responderoferta'),
    url(r'^listar-ofertas/', lista_sin_transporte, name='listaparaofertar'),
    url(r'^ofrecer-transporte/(?P<id_ped>\d*)$', OfertarTransporte, name='ofrecertrans'),
    url(r'^listar-proceso/', lista_en_proceso, name='listaproceso'),
    url(r'^responder-transport/(?P<id_proc_pedido>\d*)$', ResponderTransportes, name='respondertransport'),
    url(r'^eliminar-oferta/(?P<id_proc_pedido>\d*)$', Eliminar_ofert_transport, name='eliminaroferta'),
    url(r'^solicitar-seg/(?P<id_proc_pedido>\d*)$', SolicitarSeguimientos, name='solicitarseg'),
    url(r'^mis-seguimientos/', lista_en_seguimiento, name='misseguimientos'),
    url(r'^lista-seguimiento/', seguimiento_admin, name='listaseguimientos'),
    url(r'^administrar-seguimiento/(?P<id_seguimiento>\d*)$', AdministrarSeguimientos, name='administrarseguimiento'),
]

feria_virtual/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from apps.usuarios.views import RegistroUsuario
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.contrib.auth import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include ('apps.base.urls'), name='base'),
    url(r'^registrarse$', RegistroUsuario.as_view(), name='registrarse'),
    url(r'^login/', auth_views.LoginView.as_view(template_name='feria/login.html'), name='login'),
    url(r'^principal/', include ('apps.sistema.urls'), name='base'),
    #url(r'^logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/base/models.py
from django.db import models

# Create your models here.

apps/base/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
# Create your views here.


def index(request):
	return render(request, 'feria/index.html')

templates/base/base_logeado.html
{% load static %}

<html>

<head>
    {% block extrastatic %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Maipo Grande</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/datepicker3.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    {% endblock %}

    {% block title %}

    {% endblock%}

    <!--Custom Font-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span></button>
                <a class="navbar-brand" href="#"><span>Maipo</span> Grande</a>
                <ul class="nav navbar-top-links navbar-right">
                    <li class="dropdown"><a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                            <em class="fa fa-envelope"></em><span class="label label-danger">2</span>
                        </a>
                        <ul class="dropdown-menu dropdown-messages">
                            <li>
                                <div class="dropdown-messages-box"><a href="profile.html" class="pull-left">
                                        <img alt="image" class="img-circle" src="http://placehold.it/40/30a5ff/fff">
                                    </a>
                                    <div class="message-body"><small class="pull-right">hace 25 minutos</small>
                                        <a href="#"><strong>Jaime</strong> ha enviado un <strong>Ingreso de Solicitud
                                                Compra</strong>.</a>
                                        <br /><small class="text-muted">15:27 pm - 08/10/2020</small></div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="dropdown-messages-box"><a href="profile.html" class="pull-left">
                                        <img alt="image" class="img-circle" src="http://placehold.it/40/30a5ff/fff">
                                    </a>
                                    <div class="message-body"><small class="pull-right">hace 1 hora</small>
                                        <a href="#"><strong>Francisca</strong> ha solicitado una <strong>activación de
                                                cuenta</strong>.</a>
                                        <br /><small class="text-muted">12:27 pm - 03/10/2020</small></div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <div class="all-button"><a href="#">
                                        <em class="fa fa-inbox"></em> <strong>Todas las Notificaciones</strong>
                                    </a></div>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown"><a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                            <em class="fa fa-bell"></em><span class="label label-info">18</span>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li><a href="#">
                                    <div><em class="fa fa-envelope"></em> 1 Ayuda
                                        <span class="pull-right text-muted small">3 mins ago</span></div>
                                </a></li>
                            <li class="divider"></li>
                            <li><a href="#">
                                    <div><em class="fa fa-book"></em> 12 Ventas Activas
                                        <span class="pull-right text-muted small">4 mins ago</span></div>
                                </a></li>
                            <li class="divider"></li>
                            <li><a href="#">
                                    <div><em class="fa fa-user"></em> 5 Solicitudes de Cuentas
                                        <span class="pull-right text-muted small">4 mins ago</span></div>
                                </a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div><!-- /.container-fluid -->
    </nav>
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <div class="profile-sidebar">
            <div class="profile-userpic">
                <img src="http://placehold.it/50/30a5ff/fff" class="img-responsive" alt="">
            </div>
            <div class="profile-usertitle">
                <div class="profile-usertitle-name">{{ request.user.username }}</div>
                <div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="divider"></div>
        <!--
        <form role="search">  
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
            </div>
        </form>
        -->


{% if request.user.is_staff %}

<ul class="nav menu">
    <li><a href=""><em class="fa fa-user">&nbsp;</em> Mi Perfil</a></li>
    <li><a href="{% url 'sistema:index' %}"><em class="fa fa-dashboard">&nbsp;</em> Resumen</a></li>
    <li><a href="{% url 'sistema:listaprod' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Productos publicados</a></li>
    <li><a href="{% url 'sistema:listaped' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Solicitudes de clientes</a></li>
    <li><a href="{% url 'sistema:listaseguimientos' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Seguimiento</a></li>
    <li><a href="{% url 'sistema:usuarios' %}"><em class="fa fa-users">&nbsp;</em> Miembros</a></li>
    <li><a href="{% url 'login' %}"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>
</ul>

{% else %}

    {% if request.user.tipo_usuario == 'productor' %}

    <ul class="nav menu">
        <li><a href=""><em class="fa fa-user">&nbsp;</em> Mi Perfil</a></li>
        <li><a href="{% url 'sistema:mi-contrato' %}"><em class="fa fa-dashboard">&nbsp;</em> Mi contrato</a></li>
        <li><a href="{% url 'sistema:index' %}"><em class="fa fa-dashboard">&nbsp;</em> Resumen</a></li>
        <li><a href="{% url 'sistema:regprod' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Agregar Productos </a></li>
        <li><a href="{% url 'sistema:listasinofertas' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Solicitudes de clientes </a></li>
        <li><a href="{% url 'login' %}"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>
    </ul>

    {% else %}

        {% if request.user.tipo_usuario == 'interno' %}

        <ul class="nav menu">
            <li><a href=""><em class="fa fa-user">&nbsp;</em> Mi Perfil</a></li>
            <li><a href="{% url 'sistema:mi-contrato' %}"><em class="fa fa-dashboard">&nbsp;</em> Mi contrato</a></li>
            <li><a href="{% url 'sistema:index' %}"><em class="fa fa-dashboard">&nbsp;</em> Resumen</a></li>
            <li><a href="{% url 'sistema:listaprod' %}}"><em class="fa fa-shopping-cart">&nbsp;</em> Lista de productos </a></li>
            <li><a href="{% url 'login' %}"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>
        </ul>

        {% else %}
    
            {% if request.user.tipo_usuario == 'externo' %}

            <ul class="nav menu">
                <li><a href=""><em class="fa fa-user">&nbsp;</em> Mi Perfil</a></li>
                <li><a href="{% url 'sistema:mi-contrato' %}"><em class="fa fa-dashboard">&nbsp;</em> Mi contrato</a></li>
                <li><a href="{% url 'sistema:index' %}"><em class="fa fa-dashboard">&nbsp;</em> Resumen</a></li>
                <li><a href="{% url 'sistema:solped' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Solicitar productos </a></li>
                <li><a href="{% url 'sistema:mispedidos' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Solicitudes pendientes </a></li>
                <li><a href="{% url 'sistema:listaproceso' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Solicitudes en proceso </a></li>
                <li><a href="{% url 'sistema:misseguimientos' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Seguir mis pedidos </a></li>
                <li><a href="{% url 'sistema:listaprod' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Productos publicados </a></li>
                <li><a href="{% url 'login' %}"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>
            </ul>

            {% else %}
    
                {% if request.user.tipo_usuario == 'consultor' %}

                <ul class="nav menu">
                    <li><a href=""><em class="fa fa-user">&nbsp;</em> Mi Perfil</a></li>
                    <li><a href="{% url 'sistema:mi-contrato' %}"><em class="fa fa-dashboard">&nbsp;</em> Mi contrato</a></li>
                    <li><a href="{% url 'sistema:index' %}"><em class="fa fa-dashboard">&nbsp;</em> Resumen</a></li>
                    <li><a href="{% url 'login' %}"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>
                </ul>

                {% else %}
    
                    {% if request.user.tipo_usuario == 'transportista' %}

                    <ul class="nav menu">
                        <li><a href=""><em class="fa fa-user">&nbsp;</em> Mi Perfil</a></li>
                        <li><a href="{% url 'sistema:mi-contrato' %}"><em class="fa fa-dashboard">&nbsp;</em> Mi contrato</a></li>
                        <li><a href="{% url 'sistema:index' %}"><em class="fa fa-dashboard">&nbsp;</em> Resumen</a></li>
                        <li><a href="{% url 'sistema:regptrans' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Publicar Transporte </a></li>
                        <li><a href="{% url 'sistema:listaparaofertar' %}"><em class="fa fa-shopping-cart">&nbsp;</em> Ofertar transporte interno </a></li>
                        <li><a href="{% url 'login' %}"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>
                    </ul>

                    {% endif %}
                {% endif %}
            {% endif %}
        {% endif %}
    {% endif %}
{% endif %}

</div>

{% block content %}




{% endblock %}

    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/chart.min.js' %}"></script>
    <script src="{% static 'js/chart-data.js' %}"></script>
    <script src="{% static 'js/easypiechart.js' %}"></script>
    <script src="{% static 'js/easypiechart-data.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="https://account.snatchbot.me/script.js"></script><script>window.sntchChat.Init(140048)</script> 
    <script>
        window.onload = function () {
            var chart1 = document.getElementById("line-chart").getContext("2d");
            window.myLine = new Chart(chart1).Line(lineChartData, {
                responsive: true,
                scaleLineColor: "rgba(0,0,0,.2)",
                scaleGridLineColor: "rgba(0,0,0,.05)",
                scaleFontColor: "#c5c7cc"
            });
        };
    </script>

</body>

</html>