apps/base/urls.py
from django.conf.urls import url, include
from apps.base.views import index

from django.urls import include, path

app_name = "base";

urlpatterns = [
url(r'^$', index,name='index'),
]

apps/sistema/urls.py
from django.conf.urls import url, include
from apps.sistema.views import index,listar_usuarios,User_edit,registrarproductos,listar_productos,Contrato,VerContrato,registrartransportes
from apps.sistema.views import solicitarpedido,listar_pedidos,AdministrarPedido,OfertaProducto,lista_ofrecer,lista_procesopedidos,ResponderOfertas
from apps.sistema.views import lista_sin_transporte,OfertarTransporte,lista_en_proceso,ResponderTransportes,Eliminar_ofert_transport,SolicitarSeguimientos
from apps.sistema.views import lista_en_seguimiento,seguimiento_admin,AdministrarSeguimientos
from django.urls import include, path

app_name = "sistema";

urlpatterns = [
    url(r'^$', index,name='index'),
    url(r'^usuarios/', listar_usuarios,name='usuarios'),
    url(r'^editar/(?P<id_user>\d*)$', User_edit, name='editar_usuario'),
    url(r'^registrarprod/', registrarproductos,name='regprod'),
    url(r'^listaprod/', listar_productos, name='listaprod'),
    url(r'^mi-contrato/',VerContrato,name='mi-contrato'),
    url(r'^contrato/', Contrato, name='regcontr'),
    url(r'^registrartrans/', registrartransportes,name='regptrans'),
    url(r'^solicitar-pedido/', solicitarpedido,name='solped'),
    url(r'^listapedid/', listar_pedidos, name='listaped'),
    url(r'^administrar-pedido/(?P<id_ped>\d*)$', AdministrarPedido, name='administrarpedido'),
    url(r'^lista-sin-ofertas/', lista_ofrecer, name='listasinofertas'),
    url(r'^oferta-transporte/(?P<id_ped>\d*)$', OfertaProducto, name='ofertatransporte'),
    url(r'^mis-pedidos/', lista_procesopedidos, name='mispedidos'),
    url(r'^responder-oferta/(?P<id_ped>\d*)$', ResponderOfertas, name='responderoferta'),
    url(r'^listar-ofertas/', lista_sin_transporte, name='listaparaofertar'),
    url(r'^ofrecer-transporte/(?P<id_ped>\d*)$', OfertarTransporte, name='ofrecertrans'),
    url(r'^listar-proceso/', lista_en_proceso, name='listaproceso'),
    url(r'^responder-transport/(?P<id_proc_pedido>\d*)$', ResponderTransportes, name='respondertransport'),
    url(r'^eliminar-oferta/(?P<id_proc_pedido>\d*)$', Eliminar_ofert_transport, name='eliminaroferta'),
    url(r'^solicitar-seg/(?P<id_proc_pedido>\d*)$', SolicitarSeguimientos, name='solicitarseg'),
    url(r'^mis-seguimientos/', lista_en_seguimiento, name='misseguimientos'),
    url(r'^lista-seguimiento/', seguimiento_admin, name='listaseguimientos'),
    url(r'^administrar-seguimiento/(?P<id_seguimiento>\d*)$', AdministrarSeguimientos, name='administrarseguimiento'),
]

feria_virtual/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from apps.usuarios.views import RegistroUsuario
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.contrib.auth import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include ('apps.base.urls'), name='base'),
    url(r'^registrarse$', RegistroUsuario.as_view(), name='registrarse'),
    url(r'^login/', auth_views.LoginView.as_view(template_name='feria/login.html'), name='login'),
    url(r'^principal/', include ('apps.sistema.urls'), name='base'),
    #url(r'^logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/sistema/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
import _datetime
from dateutil.relativedelta import relativedelta

class Contratos(models.Model):
    id_contrat = models.AutoField(primary_key=True)
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')
    rut_person = models.CharField(max_length=20)
    phone_contrat = models.IntegerField()
    emision_contrat = models.DateField(default=_datetime.date.today(),blank=True)
    fin_contrat = models.DateField(default=_datetime.date.today() + relativedelta(years = 1), blank = True)
    estado = models.BooleanField(default = False)

    class Meta:
        managed = False
        db_table = 'contratos'


class DetallCompra(models.Model):
    id_detall = models.IntegerField(primary_key=True)
    proces_venta_id_proc_venta = models.ForeignKey('ProcesVenta', models.DO_NOTHING, db_column='proces_venta_id_proc_venta')
    fecha_detall = models.DateField()
    nom_producto = models.CharField(max_length=15)
    cost_producto = models.IntegerField()
    iva_producto = models.IntegerField()
    total_compra = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'detall_compra'


class DirecExtran(models.Model):
    vent_extran_id_vent_ex = models.ForeignKey('VentExtran', models.DO_NOTHING, db_column='vent_extran_id_vent_ex')
    id_direc = models.CharField(primary_key=True, max_length=20)
    pais = models.CharField(max_length=20)
    direc_cli = models.CharField(max_length=20)
    num_calle = models.IntegerField(blank=True, null=True)
    depto = models.CharField(max_length=10, blank=True, null=True)
    localidad = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'direc_extran'


class DirecLocal(models.Model):
    id_direc = models.CharField(primary_key=True, max_length=20)
    direc_cli = models.CharField(max_length=20)
    num_calle = models.IntegerField(blank=True, null=True)
    depto = models.CharField(max_length=10, blank=True, null=True)
    region = models.CharField(max_length=20)
    comuna = models.CharField(max_length=20)
    vent_local_id_vent_loc = models.ForeignKey('VentLocal', models.DO_NOTHING, db_column='vent_local_id_vent_loc')

    class Meta:
        managed = False
        db_table = 'direc_local'


class Pedido(models.Model):
    id_ped = models.AutoField(primary_key=True)
    tipo = models.CharField(max_length=200)
    fecha = models.DateField()
    descrip = models.CharField(max_length=200)
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')
    productos_id_prod = models.ForeignKey('Productos', models.DO_NOTHING, db_column='productos_id_prod', blank=True, null=True)
    estado_admin = models.BooleanField(default = False)
    estado_productor = models.BooleanField(default = False)

    class Meta:
        managed = False
        db_table = 'pedido'


class ProcesPedido(models.Model):
    id_proc_pedido = models.AutoField(primary_key=True)
    transporte_id_trans = models.ForeignKey('Transporte', models.DO_NOTHING, db_column='transporte_id_trans')
    pedido_id_ped = models.ForeignKey(Pedido, models.DO_NOTHING, db_column='pedido_id_ped')
    estado_proceso = models.BooleanField(default = False)
    class Meta:
        managed = False
        db_table = 'proces_pedido'


class ProcesVenta(models.Model):
    id_proc_venta = models.IntegerField(primary_key=True)
    proces_pedido_id_proc_pedido = models.ForeignKey(ProcesPedido, models.DO_NOTHING, db_column='proces_pedido_id_proc_pedido')

    class Meta:
        managed = False
        db_table = 'proces_venta'


class Productos(models.Model):
    id_prod = models.AutoField(primary_key=True)
    nom_prod = models.CharField(max_length=20)
    precio_prod = models.IntegerField()
    desc_prod = models.CharField(max_length=200)
    stock_prod = models.IntegerField()
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')

    class Meta:
        managed = False
        db_table = 'productos'


class ReportMerma(models.Model):
    id_merma = models.IntegerField(primary_key=True)
    fecha_merma = models.DateField()
    descrip_merma = models.CharField(max_length=40)
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')

    class Meta:
        managed = False
        db_table = 'report_merma'


class ReportVenta(models.Model):
    id_report_vent = models.IntegerField(primary_key=True)
    prod_venta = models.CharField(max_length=20)
    cant_venta = models.IntegerField()
    total_venta = models.IntegerField()
    proces_venta_id_proc_venta = models.ForeignKey(ProcesVenta, models.DO_NOTHING, db_column='proces_venta_id_proc_venta')

    class Meta:
        managed = False
        db_table = 'report_venta'


class Reportes(models.Model):
    id_report = models.IntegerField(primary_key=True)
    fecha_report = models.DateField()
    tip_report = models.CharField(max_length=15)
    user_report = models.CharField(max_length=15)
    descrip_report = models.CharField(max_length=30)
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')

    class Meta:
        managed = False
        db_table = 'reportes'


class Seguimiento(models.Model):
    id_seguimiento = models.AutoField(primary_key=True)
    estados = (('preparando','preparando productos'),('despacho','productos despachados'),
        ('recepcionados','recepcionados por el transportista'),('viaje','en camino'),('completado','seguimiento finalizado'))
    est_seguimiento = models.CharField(max_length=50,choices=estados,default='preparando')
    pedido_id_ped = models.ForeignKey(Pedido, models.DO_NOTHING, db_column='pedido_id_ped')
    proces_pedido_id_proc_pedido = models.ForeignKey(ProcesPedido, models.DO_NOTHING, db_column='proces_pedido_id_proc_pedido')

    class Meta:
        managed = False
        db_table = 'seguimiento'


class Transporte(models.Model):
    id_trans = models.AutoField(primary_key=True)
    tip_transporte = models.CharField(max_length=15)
    tamano_trans = models.IntegerField()
    capacidad_trans = models.IntegerField()
    refrigeracion_trans = models.CharField(max_length=10)
    fecha_trans = models.DateField()
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')

    class Meta:
        managed = False
        db_table = 'transporte'


class UsuariosUsuarios(models.Model):
    id_user = models.AutoField(primary_key=True)
    password = models.CharField(max_length=128, blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=50, blank=True, null=True)
    email = models.CharField(unique=True, max_length=254, blank=True, null=True)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    direccion = models.CharField(max_length=50, blank=True, null=True)
    is_active = models.BooleanField()
    is_staff = models.BooleanField()
    tipo_usuario = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'usuarios_usuarios'


class VentExtran(models.Model):
    id_vent_ex = models.CharField(primary_key=True, max_length=10)
    proces_venta_id_proc_venta = models.ForeignKey(ProcesVenta, models.DO_NOTHING, db_column='proces_venta_id_proc_venta')
    nom_cli = models.CharField(max_length=20)
    ape_pat = models.CharField(max_length=20)
    ape_mat = models.CharField(max_length=20)
    email = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'vent_extran'


class VentLocal(models.Model):
    id_vent_loc = models.CharField(primary_key=True, max_length=10)
    proces_venta_id_proc_venta = models.ForeignKey(ProcesVenta, models.DO_NOTHING, db_column='proces_venta_id_proc_venta')
    nom_cli = models.CharField(max_length=20)
    ape_pat = models.CharField(max_length=20)
    ape_mat = models.CharField(max_length=20)
    email = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'vent_local'

templates/feria/contrato.html
{% extends 'base/base_logeado.html' %}



{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

    <div class="row">
        <ol class="breadcrumb">
            <li><a href="#">
                    <em class="fa fa-home"></em>
                </a></li>
            <li class="active">Contrato</li>
        </ol>
    </div>
    <!--/.row-->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Solicitar contrato</h1>
        </div>
    </div>
    <!--/.row-->
    <div class="panel panel-default">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="tab1">
                    	<table class="table table-bordered">
							<center>
							<h2>Proporciona tu informacion personal</h2>
								<div class="container">
									<form method="POST">
										{% csrf_token %}
										<input type="text" name="usuarios_usuarios_id_user" class="form-control" required="" id="id_usuarios_usuarios_id_user" value="{{ request.user.id_user }}" style="display: none;">
										<h2>Rut</h2>
										{{ form.rut_person }}
										<h2>Telefono</h2>
										{{ form.phone_contrat }}
										<h3>(Las fechas estimadas para el contrato se generaran de forma automatica)</h3>

										<br>
										<br>
										<button class="btn btn-primary" type="submit">Solicitar</button>
									</form>
								</div>

							</center>
                	</div>
                </div>
            </div>
        </div>
        	<!--/.panel-->
    </div>
            <!--/.col-->
</div>   
    	<!--/.main-->
{% endblock %}

templates/feria/index.html
{% extends 'base/base.html' %}
{% block content %}

{% endblock %}

templates/feria/lista-pedidos.html
{% extends 'base/base_logeado.html' %}

{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

        <div class="row">
            <ol class="breadcrumb">
                <li><a href="#">
                        <em class="fa fa-home"></em>
                    </a></li>
                <li class="active">Lista de productos</li>
            </ol>
        </div>
        <!--/.row-->

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Lista de productos</h1>
            </div>
        </div>
        <!--/.row-->
        <div class="panel panel-default">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1">

							<table class="table table-bordered" >
								<thead>
									<tr>
										<th><center>Tipo</center></th>
										<th><center>Fecha Solicitada</center></th>
										<th><center>Descripcion</center></th>
										<th><center>Usuario</center></th>
										<th><center>Estado</center></th>
										<th><center>Accion</center></th>
									</tr>
								</thead>

								<tbody>


							<div>
								<h1 style="text-align: center;"> Lista de Productos</h1>
							</div>

							{% load static %}

									{% if pedidos %}
									{% for pedido in pedidos %}
										
									<tr>
										<td><center>{{ pedido.tipo }}</center></td>
										<td><center>{{ pedido.fecha }}</center></td>
										<td><center>{{ pedido.descrip }}</center></td>
										<td><center>{{ pedido.usuarios_usuarios_id_user.username }}</center></td>
									{% if pedido.estado_admin == False %}
										<td><center>En proceso</center></td>
									{% else %}
										<td><center>Aprobado</center></td>
									{% endif %}
									{% if pedido.estado_admin == False %}
										<td> 
											<center>
												<a class="btn btn-primary" href="{% url 'sistema:administrarpedido' pedido.id_ped %}">Aprobar</a>
											</center>
										</td>
									{% else %}
										<td><center>Listo</center></td>
									{% endif %}

									</tr>

									{% endfor %}
									{% else %}

									<h1>No hay solicitudes</h1>

									{% endif %}

								</tbody>

							</table>
                        </div>
                    </div>
                </div>
            </div>
            	<!--/.panel-->
        </div>
            <!--/.col-->
    </div>   
    	<!--/.main-->

{% endblock %}

templates/feria/lista-productos.html
{% extends 'base/base_logeado.html' %}

{% block content %}







<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

        <div class="row">
            <ol class="breadcrumb">
                <li><a href="#">
                        <em class="fa fa-home"></em>
                    </a></li>
                <li class="active">Lista de productos</li>
            </ol>
        </div>
        <!--/.row-->

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Lista de productos</h1>
            </div>
        </div>
        <!--/.row-->
        <div class="panel panel-default">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1">
							<table class="table table-bordered" >
								<thead>
									<tr>
										<th>Nombre Producto</th>
										<th>Precio Producto</th>
										<th>Stock</th>
										<th>Vendedor</th>
									</tr>
								</thead>

								<tbody>
									{% load static %}
									{% if productos %}
										{% for p in productos %}
											<tr>
												<td >{{ p.0 }}</td>
												<td >{{ p.1 }}</td>
												<td >{{ p.2 }}</td>
												<td >{{ p.3 }}</td>
											</tr>
										{% endfor %}
									{% else %}
									<h1>No hay productos</h1>
									{% endif %}
								</tbody>
							</table>
                        </div>
                    </div>
                </div>
            </div>
            	<!--/.panel-->
        </div>
            <!--/.col-->
    </div>   
    	<!--/.main-->



{% endblock %}

templates/feria/login.html
{% load static %}

{% block extrastatic %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock %}

{% block content %}

<div class="divlogin">

<hgroup>
	<h1>Maipo Grande</h1>
	<a class="back" href="{% url 'base:index' %}">volver al inicio</a>
</hgroup>

<form method="post">
{% csrf_token %}

	<div class="group">
	  <input type="text" name="username"><span class="highlight"></span><span class="bar"></span>
	  <label for="username">Usuario</label>
	</div>

	<div class="group" id="contra">
	  <input type="password" name="password"><span class="highlight"></span><span class="bar"></span>
	  <label for="password">Contraseña</label>
	</div>

	<div id="botones">
		<button type="submit" class="button buttonBlue" value="Ingresar" >Iniciar Sesión
			<div class="ripples buttonRipples" id="botonlog"><span class="ripplesCircle"></span></div>
		</button>
	</div>

	<div class="new-account">
		<a href="{% url 'registrarse' %}">crear cuenta</a>
	</div>

  </form>
  
  <footer><a href="https://www.duoc.cl"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Logo_DuocUC.svg/800px-Logo_DuocUC.svg.png"></a>
	<p>GitHub - <a href="https://github.com/JKMatta/FeriaVirtual" target="_blank">Repositorio</a></p>
  </footer>


{% endblock %}
<script src="{% static 'js/login.js' %}"></script>

templates/feria/mis-seguimientos.html
{% extends 'base/base_logeado.html' %}

{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

        <div class="row">
            <ol class="breadcrumb">
                <li><a href="#">
                        <em class="fa fa-home"></em>
                    </a></li>
                <li class="active">Seguimiento</li>
            </ol>
        </div>
        <!--/.row-->

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Estado de mis productos</h1>
            </div>
        </div>
        <!--/.row-->
        <div class="panel panel-default">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1">
<table class="table table-bordered" style="margin-left: 5%;margin-right: 5%; width: 90%;">
	<thead>
		<tr>
			<th><center>Mi producto</center></th>
			<th><center>Estado actual</center></th>
		</tr>
	</thead>

<tbody>


{% load static %}

	{% if seguimientos %}
	{% for seguimiento in seguimientos %}

		{% if seguimiento.pedido_id_ped.usuarios_usuarios_id_user.id_user == request.user.id_user %}

			<tr>
				<td><center>{{ seguimiento.pedido_id_ped.tipo }}</center></td>
				<td><center>{{ seguimiento.est_seguimiento }}</center></td>
			</tr>

		{% endif %}

	{% endfor %}
	{% else %}

	<h1>No has solicitado seguimientos</h1>

	{% endif %}

</tbody>

</table>
                        </div>
                    </div>
                </div>
            </div>
            	<!--/.panel-->
        </div>
            <!--/.col-->
    </div>   
    	<!--/.main-->


{% endblock %}

templates/feria/registro.html
{% load static %}

{% block extrastatic %}
<link rel="stylesheet" href="{% static 'css/newaccount.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock %}

{% block content %}
<hgroup>
	<h1>Maipo Grande</h1>
	<a class="back" href="{% url 'base:index' %}">volver al inicio</a>
</hgroup>
<form method="post">
{% csrf_token %}

<div class="group">
  <h2>Nueva cuenta</h2>
</div>

<div class="group">
  <input type="text" name="first_name"><span class="highlight"></span><span class="bar"></span>
  <label>Ingrese su Nombre</label>
		  {% for error in form.first_name.errors %}
			<div class="alert alert-danger">
				<strong> Debe ingresar al menos un nombre </strong>
			</div>
		{% endfor %}
</div>

<div class="group">
  <input type="text" name="last_name"><span class="highlight"></span><span class="bar"></span>
  <label>Ingrese sus apellidos</label>
		  {% for error in form.last_name.errors %}
			<div class="alert alert-danger">
				<strong> Debe ingresar al menos un apellido </strong>
			</div>
		{% endfor %}
</div>

<div class="group">
  <input type="text" name="username"><span class="highlight"></span><span class="bar"></span>
  <label>Nombre de usuario</label>
		{% for error in form.username.errors %}
			<div class="alert alert-danger">
				<strong> Debe ingresar un nombre de usuario </strong>
			</div>
		{% endfor %}
</div>

<div class="group">
  <input type="email" name="email"><span class="highlight"></span><span class="bar"></span>
  <label>Ingrese su correo electrónico</label>
		{% for error in form.email.errors %}
			<div class="alert alert-danger">
				<strong> Debe ingresar un correo valido </strong>
			</div>
		{% endfor %}
</div>

<div class="group">
  <input type="password" name="password1"><span class="highlight"></span><span class="bar"></span>
  <label>Ingrese su contraseña</label>
</div>

<div class="group">
  <input type="password" name="password2"><span class="highlight"></span><span class="bar"></span>
  <label>Repetir contraseña</label>
		{% for error in form.first_name.errors %}
			<div class="alert alert-danger">
				<strong> Las contraseñas no coinciden </strong>
			</div>
		{% endfor %}
</div>

<button type="submit" class="button buttonBlue" id="boton">Crear Cuenta
  <div class="ripples buttonRipples"><span class="ripplesCircle"></span></div>
</button>

<div class="new-account">
	<a href="{% url 'login' %}">Ya tengo cuenta</a>
</div>
</form>

<footer><a href="https://www.duoc.cl"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Logo_DuocUC.svg/800px-Logo_DuocUC.svg.png"></a>
<p>GitHub - <a href="https://github.com/JKMatta/FeriaVirtual" target="_blank">Repositorio</a></p>
</footer>

{% endblock %}
<script src="{% static 'js/newaccount.js' %}"></script>

templates/feria/ver-contrato.html
{% extends 'base/base_logeado.html' %}

{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

    <div class="row">
        <ol class="breadcrumb">
            <li><a href="#">
                    <em class="fa fa-home"></em>
                </a></li>
            <li class="active">Contrato</li>
        </ol>
    </div>
    <!--/.row-->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Informacion de contrato</h1>
        </div>
    </div>
    <!--/.row-->
    <div class="panel panel-default">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="tab1">
                    	<table class="table table-bordered">
						{% if contra %}
							{% for contrato in contra %}
							    <div class="col-md-3">
					                <div class="row">
					                    <h4 style="padding-left: 3%; margin: 0%;">Rut</h4>
					                    <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
					                    	<input class="form-control" type="text" name="rut_person" value="{{ contrato.rut_person }}" maxlength="200" required="" id="id_descrip" disabled>
					                    </div>
					                </div>
					            </div>
					            <div class="col-md-3">
					                <div class="row">
					                    <h4 style="padding-left: 3%; margin: 0%;">Telefono</h4>
					                    <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
					                    	<input class="form-control" type="text" name="phone_contrat" value="{{ contrato.phone_contrat }}" maxlength="200" required="" id="id_phone_contrat" disabled>
					                    </div>
					                </div>
					            </div>
					            <div class="col-md-3">
					                <div class="row">
					                    <h4 style="padding-left: 3%; margin: 0%;">Fecha emitida</h4>
					                    <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
					                    	<input class="form-control" type="text" name="emision_contrat" value="{{ contrato.emision_contrat }}" maxlength="200" required="" id="id_emision_contrat" disabled>
					                    </div>
					                </div>
					            </div>
					            <div class="col-md-3">
					                <div class="row">
					                    <h4 style="padding-left: 3%; margin: 0%;">Fin del contrato</h4>
					                    <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
					                    	<input class="form-control" type="text" name="fin_contrat" value="{{ contrato.fin_contrat }}" maxlength="200" required="" id="id_fin_contrat" disabled>
					                    </div>
					                </div>
					            </div>
					            {% if contrato.estado == 0 %}
					            <div class="col-md-3">
					                <div class="row">
					                    <h4 style="padding-left: 3%; margin: 0%;">Estado</h4>
					                    <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
					                    	<input class="form-control" type="text" name="estado" value="En revision" maxlength="200" required="" id="id_estado" disabled>
					                    </div>
					                </div>
					            </div>
								{% else %}
					            <div class="col-md-3">
					                <div class="row">
					                    <h4 style="padding-left: 3%; margin: 0%;">Estado</h4>
					                    <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
					                    	<input class="form-control" type="text" name="estado" value="Aceptado" maxlength="200" required="" id="id_estado" disabled>
					                    </div>
					                </div>
					            </div>
								{% endif %}

							</center>
							{% endfor %}
						{% else %}

							<h1 style="margin-left: 5%;">Solicitar contrato</h1>
							<a class="btn btn-primary" href="{% url 'sistema:regcontr' %}" style="margin-left: 5%;">Pedir contrato</a>

						{% endif %}
                	</div>
                </div>
            </div>
        </div>
        	<!--/.panel-->
    </div>
            <!--/.col-->
</div>   
    	<!--/.main-->

{% endblock %}