apps/sistema/urls.py
from django.conf.urls import url, include
from apps.sistema.views import index,listar_usuarios,User_edit,registrarproductos,listar_productos,Contrato,VerContrato,registrartransportes
from apps.sistema.views import solicitarpedido,listar_pedidos,AdministrarPedido,OfertaProducto,lista_ofrecer,lista_procesopedidos,ResponderOfertas
from apps.sistema.views import lista_sin_transporte,OfertarTransporte,lista_en_proceso,ResponderTransportes,Eliminar_ofert_transport,SolicitarSeguimientos
from apps.sistema.views import lista_en_seguimiento,seguimiento_admin,AdministrarSeguimientos
from django.urls import include, path

app_name = "sistema";

urlpatterns = [
    url(r'^$', index,name='index'),
    url(r'^usuarios/', listar_usuarios,name='usuarios'),
    url(r'^editar/(?P<id_user>\d*)$', User_edit, name='editar_usuario'),
    url(r'^registrarprod/', registrarproductos,name='regprod'),
    url(r'^listaprod/', listar_productos, name='listaprod'),
    url(r'^mi-contrato/',VerContrato,name='mi-contrato'),
    url(r'^contrato/', Contrato, name='regcontr'),
    url(r'^registrartrans/', registrartransportes,name='regptrans'),
    url(r'^solicitar-pedido/', solicitarpedido,name='solped'),
    url(r'^listapedid/', listar_pedidos, name='listaped'),
    url(r'^administrar-pedido/(?P<id_ped>\d*)$', AdministrarPedido, name='administrarpedido'),
    url(r'^lista-sin-ofertas/', lista_ofrecer, name='listasinofertas'),
    url(r'^oferta-transporte/(?P<id_ped>\d*)$', OfertaProducto, name='ofertatransporte'),
    url(r'^mis-pedidos/', lista_procesopedidos, name='mispedidos'),
    url(r'^responder-oferta/(?P<id_ped>\d*)$', ResponderOfertas, name='responderoferta'),
    url(r'^listar-ofertas/', lista_sin_transporte, name='listaparaofertar'),
    url(r'^ofrecer-transporte/(?P<id_ped>\d*)$', OfertarTransporte, name='ofrecertrans'),
    url(r'^listar-proceso/', lista_en_proceso, name='listaproceso'),
    url(r'^responder-transport/(?P<id_proc_pedido>\d*)$', ResponderTransportes, name='respondertransport'),
    url(r'^eliminar-oferta/(?P<id_proc_pedido>\d*)$', Eliminar_ofert_transport, name='eliminaroferta'),
    url(r'^solicitar-seg/(?P<id_proc_pedido>\d*)$', SolicitarSeguimientos, name='solicitarseg'),
    url(r'^mis-seguimientos/', lista_en_seguimiento, name='misseguimientos'),
    url(r'^lista-seguimiento/', seguimiento_admin, name='listaseguimientos'),
    url(r'^administrar-seguimiento/(?P<id_seguimiento>\d*)$', AdministrarSeguimientos, name='administrarseguimiento'),
]

feria_virtual/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from apps.usuarios.views import RegistroUsuario
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.contrib.auth import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include ('apps.base.urls'), name='base'),
    url(r'^registrarse$', RegistroUsuario.as_view(), name='registrarse'),
    url(r'^login/', auth_views.LoginView.as_view(template_name='feria/login.html'), name='login'),
    url(r'^principal/', include ('apps.sistema.urls'), name='base'),
    #url(r'^logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/sistema/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
import _datetime
from dateutil.relativedelta import relativedelta

class Contratos(models.Model):
    id_contrat = models.AutoField(primary_key=True)
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')
    rut_person = models.CharField(max_length=20)
    phone_contrat = models.IntegerField()
    emision_contrat = models.DateField(default=_datetime.date.today(),blank=True)
    fin_contrat = models.DateField(default=_datetime.date.today() + relativedelta(years = 1), blank = True)
    estado = models.BooleanField(default = False)

    class Meta:
        managed = False
        db_table = 'contratos'


class DetallCompra(models.Model):
    id_detall = models.IntegerField(primary_key=True)
    proces_venta_id_proc_venta = models.ForeignKey('ProcesVenta', models.DO_NOTHING, db_column='proces_venta_id_proc_venta')
    fecha_detall = models.DateField()
    nom_producto = models.CharField(max_length=15)
    cost_producto = models.IntegerField()
    iva_producto = models.IntegerField()
    total_compra = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'detall_compra'


class DirecExtran(models.Model):
    vent_extran_id_vent_ex = models.ForeignKey('VentExtran', models.DO_NOTHING, db_column='vent_extran_id_vent_ex')
    id_direc = models.CharField(primary_key=True, max_length=20)
    pais = models.CharField(max_length=20)
    direc_cli = models.CharField(max_length=20)
    num_calle = models.IntegerField(blank=True, null=True)
    depto = models.CharField(max_length=10, blank=True, null=True)
    localidad = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'direc_extran'


class DirecLocal(models.Model):
    id_direc = models.CharField(primary_key=True, max_length=20)
    direc_cli = models.CharField(max_length=20)
    num_calle = models.IntegerField(blank=True, null=True)
    depto = models.CharField(max_length=10, blank=True, null=True)
    region = models.CharField(max_length=20)
    comuna = models.CharField(max_length=20)
    vent_local_id_vent_loc = models.ForeignKey('VentLocal', models.DO_NOTHING, db_column='vent_local_id_vent_loc')

    class Meta:
        managed = False
        db_table = 'direc_local'


class Pedido(models.Model):
    id_ped = models.AutoField(primary_key=True)
    tipo = models.CharField(max_length=200)
    fecha = models.DateField()
    descrip = models.CharField(max_length=200)
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')
    productos_id_prod = models.ForeignKey('Productos', models.DO_NOTHING, db_column='productos_id_prod', blank=True, null=True)
    estado_admin = models.BooleanField(default = False)
    estado_productor = models.BooleanField(default = False)

    class Meta:
        managed = False
        db_table = 'pedido'


class ProcesPedido(models.Model):
    id_proc_pedido = models.AutoField(primary_key=True)
    transporte_id_trans = models.ForeignKey('Transporte', models.DO_NOTHING, db_column='transporte_id_trans')
    pedido_id_ped = models.ForeignKey(Pedido, models.DO_NOTHING, db_column='pedido_id_ped')
    estado_proceso = models.BooleanField(default = False)
    class Meta:
        managed = False
        db_table = 'proces_pedido'


class ProcesVenta(models.Model):
    id_proc_venta = models.IntegerField(primary_key=True)
    proces_pedido_id_proc_pedido = models.ForeignKey(ProcesPedido, models.DO_NOTHING, db_column='proces_pedido_id_proc_pedido')

    class Meta:
        managed = False
        db_table = 'proces_venta'


class Productos(models.Model):
    id_prod = models.AutoField(primary_key=True)
    nom_prod = models.CharField(max_length=20)
    precio_prod = models.IntegerField()
    desc_prod = models.CharField(max_length=200)
    stock_prod = models.IntegerField()
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')

    class Meta:
        managed = False
        db_table = 'productos'


class ReportMerma(models.Model):
    id_merma = models.IntegerField(primary_key=True)
    fecha_merma = models.DateField()
    descrip_merma = models.CharField(max_length=40)
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')

    class Meta:
        managed = False
        db_table = 'report_merma'


class ReportVenta(models.Model):
    id_report_vent = models.IntegerField(primary_key=True)
    prod_venta = models.CharField(max_length=20)
    cant_venta = models.IntegerField()
    total_venta = models.IntegerField()
    proces_venta_id_proc_venta = models.ForeignKey(ProcesVenta, models.DO_NOTHING, db_column='proces_venta_id_proc_venta')

    class Meta:
        managed = False
        db_table = 'report_venta'


class Reportes(models.Model):
    id_report = models.IntegerField(primary_key=True)
    fecha_report = models.DateField()
    tip_report = models.CharField(max_length=15)
    user_report = models.CharField(max_length=15)
    descrip_report = models.CharField(max_length=30)
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')

    class Meta:
        managed = False
        db_table = 'reportes'


class Seguimiento(models.Model):
    id_seguimiento = models.AutoField(primary_key=True)
    estados = (('preparando','preparando productos'),('despacho','productos despachados'),
        ('recepcionados','recepcionados por el transportista'),('viaje','en camino'),('completado','seguimiento finalizado'))
    est_seguimiento = models.CharField(max_length=50,choices=estados,default='preparando')
    pedido_id_ped = models.ForeignKey(Pedido, models.DO_NOTHING, db_column='pedido_id_ped')
    proces_pedido_id_proc_pedido = models.ForeignKey(ProcesPedido, models.DO_NOTHING, db_column='proces_pedido_id_proc_pedido')

    class Meta:
        managed = False
        db_table = 'seguimiento'


class Transporte(models.Model):
    id_trans = models.AutoField(primary_key=True)
    tip_transporte = models.CharField(max_length=15)
    tamano_trans = models.IntegerField()
    capacidad_trans = models.IntegerField()
    refrigeracion_trans = models.CharField(max_length=10)
    fecha_trans = models.DateField()
    usuarios_usuarios_id_user = models.ForeignKey('UsuariosUsuarios', models.DO_NOTHING, db_column='usuarios_usuarios_id_user')

    class Meta:
        managed = False
        db_table = 'transporte'


class UsuariosUsuarios(models.Model):
    id_user = models.AutoField(primary_key=True)
    password = models.CharField(max_length=128, blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=50, blank=True, null=True)
    email = models.CharField(unique=True, max_length=254, blank=True, null=True)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    direccion = models.CharField(max_length=50, blank=True, null=True)
    is_active = models.BooleanField()
    is_staff = models.BooleanField()
    tipo_usuario = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'usuarios_usuarios'


class VentExtran(models.Model):
    id_vent_ex = models.CharField(primary_key=True, max_length=10)
    proces_venta_id_proc_venta = models.ForeignKey(ProcesVenta, models.DO_NOTHING, db_column='proces_venta_id_proc_venta')
    nom_cli = models.CharField(max_length=20)
    ape_pat = models.CharField(max_length=20)
    ape_mat = models.CharField(max_length=20)
    email = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'vent_extran'


class VentLocal(models.Model):
    id_vent_loc = models.CharField(primary_key=True, max_length=10)
    proces_venta_id_proc_venta = models.ForeignKey(ProcesVenta, models.DO_NOTHING, db_column='proces_venta_id_proc_venta')
    nom_cli = models.CharField(max_length=20)
    ape_pat = models.CharField(max_length=20)
    ape_mat = models.CharField(max_length=20)
    email = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'vent_local'

templates/feria/administrador/administrar-pedido.html
{% extends 'base/base_logeado.html' %}




{% block content %}


<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

        <div class="row">
            <ol class="breadcrumb">
                <li><a href="#">
                        <em class="fa fa-home"></em>
                    </a></li>
                <li class="active">Solicitudes</li>
            </ol>
        </div>
        <!--/.row-->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Solicitud del cliente</h1>
            </div>
        </div>
        <!--/.row-->
        <div class="panel panel-default">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1">
							<table class="table table-bordered">
							<br>
							<center>	
								<div class="container">
									<form method="POST">
										{% csrf_token %}
									    <div class="col-md-3">
							                <div class="row">
							                    <h4 style="padding-left: 3%; margin: 0%;">Tipo de producto</h4>
							                    <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
							                    	<input class="form-control" type="text" name="tipo" value="{{ form.tipo.value }}" maxlength="200" required="" id="id_tipo" disabled>
							                    </div>
							                </div>
							            </div>
							            <div class="col-md-3">
							                <div class="row">
							                    <h4 style="padding-left: 3%; margin: 0%;">Fecha solicitada</h4>
							                    <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
							                    	<input class="form-control" type="text" name="fecha" value="{{ form.fecha.value }}" required="" id="id_fecha" disabled>
							                    </div>
							                </div>
							            </div>
							            <div class="col-md-3">
							                <div class="row">
							                    <h4 style="padding-left: 3%; margin: 0%;">Descripcion</h4>
							                    <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
							                    	<input class="form-control" type="text" name="descrip" value="{{ form.descrip.value }}" maxlength="200" required="" id="id_descrip" disabled>
							                    </div>
							                </div>
							            </div>
							            <div class="col-md-3">
							                <div class="row">
							                    <h4 style="padding-left: 3%; margin: 0%;">Aprobar</h4>
							                    <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
							                    	{{ form.estado_admin }}
							                    </div>
							                </div>
							            </div>

							            <div style="display: none;">
							            {{ form.tipo }}	
							            {{ form.fecha }}
							            {{ form.descrip }}
							            </div>

							            
										<br>
										<button class="btn btn-primary" type="submit">Guardar</button>
									</form>
								</div>
							</center>
                        </div>
                    </div>
                </div>
            </div>
            	<!--/.panel-->
        </div>
            <!--/.col-->
    </div>   
    	<!--/.main-->
{% endblock %}

templates/feria/administrador/administrar-seguimiento.html
{% extends 'base/base_logeado.html' %}

{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

        <div class="row">
            <ol class="breadcrumb">
                <li><a href="#">
                        <em class="fa fa-home"></em>
                    </a></li>
                <li class="active">Lista de productos</li>
            </ol>
        </div>
        <!--/.row-->

        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Lista de productos</h1>
            </div>
        </div>
        <!--/.row-->
        <div class="panel panel-default">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1">
<table class="table table-bordered">
	<thead>
		<tr>
			<td><center>Productos</center></td>
			<td><center>Cliente</center></td>
			<td><center>Vendedor</center></td>
			<td><center>Transportista</center></td>
			<td><center>Estado actual</center></td>
			<td><center>Cambiar estado</center></td>
		</tr>
	</thead>

<tbody>


{% load static %}

	{% if seguimientos %}
	{% for seguimiento in seguimientos %}

		<tr>
			<td><center>{{ seguimiento.pedido_id_ped.tipo }}</center></td>
			<td><center>{{ seguimiento.pedido_id_ped.usuarios_usuarios_id_user.username }}</center></td>
			<td><center>{{ seguimiento.pedido_id_ped.productos_id_prod.usuarios_usuarios_id_user.username }}</center></td>
			<td><center>{{ seguimiento.proces_pedido_id_proc_pedido.transporte_id_trans.usuarios_usuarios_id_user.username }}</center></td>
			<td><center>{{ seguimiento.est_seguimiento }}</center></td>
			<td><center><a class="btn btn-primary" href="{% url 'sistema:administrarseguimiento' seguimiento.id_seguimiento %}">Actualizar</a></center></td>
		</tr>

	{% endfor %}
	{% else %}

	<h1>No has solicitado seguimientos</h1>

	{% endif %}

</tbody>

</table>
                        </div>
                    </div>
                </div>
            </div>
            	<!--/.panel-->
        </div>
            <!--/.col-->
    </div>   
    	<!--/.main-->

{% endblock %}

templates/feria/administrador/editar-usuarios.html
{% extends 'base/base_logeado.html' %}




{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

        <div class="row">
            <ol class="breadcrumb">
                <li><a href="#">
                        <em class="fa fa-home"></em>
                    </a></li>
                <li class="active">Usuarios </li>
            </ol>
        </div>
        <!--/.row-->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Actualizar usuario</h1>
            </div>
        </div>
        <!--/.row-->
        <div class="panel panel-default">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1">
							<br>
							<center>
								<div class="container">
									<form method="POST">
										{% csrf_token %}
								        <div class="panel panel-default">
								            <div class="panel-heading"><h5>Datos personales</h5></div>
								            <div class="row" style="padding: 1%; margin-left: 1%; margin-right: 1%;">
								                <div class="col-md-3">
								                    <div class="row">
								                        <h4 style="padding-left: 3%; margin: 0%;">Nombre</h4>
								                        <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
								                            <input class="form-control" type="text" name="first_name" value="{{ form.first_name.value }}" maxlength="100" required="" id="id_first_name" disabled>
								                        </div>
								                    </div>
								                </div>
								                <div class="col-md-3">
								                    <div class="row">
								                        <h4 style="padding-left: 3%; margin: 0%;">Apellido</h4>
								                        <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
								                            <input class="form-control" type="text" name="last_name" value="{{ form.last_name.value }}" maxlength="100" required="" id="id_last_name" disabled>
								                        </div>
								                    </div>
								                </div>
								                <div class="col-md-3">
								                    <div class="row">
								                        <h4 style="padding-left: 3%; margin: 0%;">Correo electronico</h4>
								                        <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
								                            <input class="form-control" type="email" name="email" value="{{ form.email.value }}" maxlength="254" required="" id="id_email" disabled>
								                        </div>
								                    </div>
								                </div>
								                <div class="col-md-3">
								                    <div class="row">
								                        <h4 style="padding-left: 3%; margin: 0%;">Nombre de usuario</h4>
								                        <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
								                            <input class="form-control" type="text" name="username" value="{{ form.username.value }}" maxlength="50" required="" id="id_username" disabled>
								                        </div>
								                    </div>
								                </div>
								                <div class="col-md-3">
								                    <div class="row">
								                        <h4 style="padding-left: 3%; margin: 0%;">Usuario activo</h4>
								                        <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
								                            {{ form.is_active }}
								                        </div>
								                    </div>
								                </div>
								            </div>
								        </div>

								        <div class="panel panel-default">
								            <div class="panel-heading"><h5>Datos del contrato</h5></div>
								            <div class="row" style="padding: 1%; margin-left: 1%; margin-right: 1%;">
								                <div class="col-md-3">
								                    <div class="row">
								                        <h4 style="padding-left: 3%; margin: 0%;">Rut</h4>
								                        <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
								                            <input class="form-control" type="text" name="rut_person" value="{{ form2.rut_person.value }}" maxlength="20" required="" id="id_rut_person" disabled>
								                        </div>
								                    </div>
								                </div>

								                <div class="col-md-3">
								                    <div class="row">
								                        <h4 style="padding-left: 3%; margin: 0%;">Telefono</h4>
								                        <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
								                            <input class="form-control" type="number" name="phone_contrat" value="{{ form2.phone_contrat.value }}" required="" id="id_phone_contrat"disabled>
								                        </div>
								                    </div>
								                </div>

								                <div class="col-md-3">
								                    <div class="row">
								                        <h4 style="padding-left: 3%; margin: 0%;">Fecha emitida</h4>
								                        <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
								                            <input class="form-control" type="text" name="emision_contrat" value="{{ form2.emision_contrat.value }}" id="id_emision_contrat" disabled>
								                        </div>
								                    </div>
								                </div>

								                <div class="col-md-3">
								                    <div class="row">
								                        <h4 style="padding-left: 3%; margin: 0%;">Fecha de termino</h4>
								                        <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
								                            <input class="form-control" type="text" name="fin_contrat" value="{{ form2.fin_contrat.value }}" id="id_fin_contrat" disabled>
								                        </div>
								                    </div>
								                </div>

								                <div class="col-md-3">
								                    <div class="row">
								                        <h4 style="padding-left: 3%; margin: 0%;">Estado del contrato</h4>
								                        <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
								                            {{ form2.estado }}
								                        </div>
								                    </div>
								                </div>

								                <div class="col-md-3">
								                    <div class="row">
								                        <h4 style="padding-left: 3%; margin: 0%;">Rol</h4>
								                        <div class="form-group" style="margin-top: 1%; margin-left: 3%; margin-right: 3%;">
								                            {{ form.tipo_usuario }}
								                        </div>
								                    </div>
								                </div>

								            </div>
								        </div>


								        <div style="display: none;">
								        	{{ form.first_name }}
								        	{{ form.last_name }}
								        	{{ form.email }}
								        	{{ form.username }}
								        	{{ form2.rut_person }}
								        	{{ form2.phone_contrat }}
								        	{{ form2.emision_contrat }}
								        	{{ form2.fin_contrat }}
								        </div>







										<br>
										<button class="btn btn-primary" type="submit">Guardar</button>
									</form>
								</div>
							</center>
                        </div>
                    </div>
                </div>
            </div>
            	<!--/.panel-->
        </div>
            <!--/.col-->
    </div>   
    	<!--/.main-->
{% endblock %}

templates/feria/administrador/estados-seguimientos.html
{% extends 'base/base_logeado.html' %}




{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

        <div class="row">
            <ol class="breadcrumb">
                <li><a href="#">
                        <em class="fa fa-home"></em>
                    </a></li>
                <li class="active">Seguimiento</li>
            </ol>
        </div>
        <!--/.row-->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Actualizar seguimiento</h1>
            </div>
        </div>
        <!--/.row-->
        <div class="panel panel-default">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1">
							<center>
									<h2>Produto: {{ adminissegui.pedido_id_ped.tipo }}</h2>	
									<h2>Estado</h2>	
								<div class="container">
									<form method="POST">
										{% csrf_token %}
										{{ form.est_seguimiento }}
										<br>
										<br>
										<button type="submit" class="btn btn-primary">Guardar</button>
									</form>
								</div>
							</center>
                        </div>
                    </div>
                </div>
            </div>
            	<!--/.panel-->
        </div>
            <!--/.col-->
    </div>   
    	<!--/.main-->
{% endblock %}